name: Instagram Bot

on:
  schedule:
    - cron: "0 12 * * *"  # runs every day

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install library
        run: pip install instagrapi

      - name: Run bot
        run: python bot.py
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
